variables:
  DOCKER_BUILDKIT: 1
# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
build-webserver:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - docker:dind
  before_script:
    - echo -n $CI_REGISTRY_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build
      -f webserver/Dockerfile.webserver
      --cache-from ${CI_REGISTRY_IMAGE}_builder
      --tag ${CI_REGISTRY_IMAGE}_builder
      --target compile-image
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push ${CI_REGISTRY_IMAGE}_builder
    - docker build
      -f webserver/Dockerfile.webserver
      --cache-from ${CI_REGISTRY_IMAGE}_builder
      --cache-from $CI_REGISTRY_IMAGE
      --tag $CI_REGISTRY_IMAGE
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push $CI_REGISTRY_IMAGE


build-update-butler:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - docker:dind
  before_script:
    - echo -n $CI_REGISTRY_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build
      -f update_butler/Dockerfile.update_butler
      --cache-from ${CI_REGISTRY_IMAGE_UPDATE_BUTLER}_builder
      --tag ${CI_REGISTRY_IMAGE_UPDATE_BUTLER}_builder
      --target compile-image
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push ${CI_REGISTRY_IMAGE_UPDATE_BUTLER}_builder
    - docker build
      -f update_butler/Dockerfile.update_butler
      --cache-from ${CI_REGISTRY_IMAGE_UPDATE_BUTLER}_builder
      --cache-from $CI_REGISTRY_IMAGE_UPDATE_BUTLER
      --tag $CI_REGISTRY_IMAGE_UPDATE_BUTLER
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push $CI_REGISTRY_IMAGE_UPDATE_BUTLER


build_bahnvorhersage:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
    - jufo_bundeswettbewerb
  services:
    - docker:dind
  before_script:
    - echo -n $CI_REGISTRY_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build
      --cache-from ${CI_REGISTRY_IMAGE_BAHNVORHERSAGE}_builder
      --tag ${CI_REGISTRY_IMAGE_BAHNVORHERSAGE}_builder
      --target compile-image
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push ${CI_REGISTRY_IMAGE_BAHNVORHERSAGE}_builder
    - docker build
      --cache-from ${CI_REGISTRY_IMAGE_BAHNVORHERSAGE}_builder
      --cache-from $CI_REGISTRY_IMAGE_BAHNVORHERSAGE
      --tag $CI_REGISTRY_IMAGE_BAHNVORHERSAGE
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push $CI_REGISTRY_IMAGE_BAHNVORHERSAGE