#Ignore everything
*

#Except
!data_analysis/
!database/
!helpers/
!ml_models/
!model_analysis/
!python/
!rtd_crawler/
!tests/
!update_butler/
!webserver/
!__init__.py
!webserverconfig.py
!requirements.txt
!api/
!parser/
!crawler/
!router/
!gtfs/

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/*~
**/__pycache__/
**/*.log
**/.DS_Store
**/Thumbs.db