TRAIN_SPEED_MS = 70  # ~ 250 km/h
MAX_METERS_DRIVING_AWAY = 30_000
MAX_SECONDS_DRIVING_AWAY = int(
    MAX_METERS_DRIVING_AWAY / TRAIN_SPEED_MS
)  # driving away for 30 km
N_MINIMAL_ROUTES_TO_DESTINATION = 8
MAX_TRANSFERS = 4
EXTRA_DURATION_FOR_SHORTER_ROUTE = (
    1.1  # 10% longer for shorter route (geo-distance) is acceptable
)

NO_TRIP_ID = 0
NO_DELAYED_TRIP_ID = 1
WALKING_TRIP_ID = 2

NO_STOP_ID = 0
MAX_EXPECTED_DELAY_SECONDS = 60 * 30
MINIMAL_DISTANCE_DIFFERENCE = 1000  # 1 km
EXTRA_TIME_BEFORE_EARLY_STOP = 60 * 60 * 2  # 2 hour
MINIMUM_TRANSFER_TIME = 60 * 3  # 3 minutes
N_ROUTES_TO_FIND = 14
