kind: Service
apiVersion: v1
metadata:
  name: db-rest-service
spec:
  selector:
    app: db-rest
  ports:
    - port: 3000 # Default port for image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-rest
  name: db-rest
  namespace: default
spec:
  selector:
    matchLabels:
      app: db-rest
  template:
    metadata:
      labels:
        app: db-rest
    spec:
      containers:
      - image: trainconnectionprediction/db-rest:6
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis
              key: url
              optional: false # same as default; "mysecret" must exist
                              # and include a key named "username"
        imagePullPolicy: Always
        name: db-rest
        resources: {}
        volumeMounts:
        - name: tz-berlin # set timezone to CEST
          mountPath: /etc/localtime
      restartPolicy: Always
      volumes:
      - name: tz-berlin  # set timezone to CEST
        hostPath:
          path: /usr/share/zoneinfo/Europe/Berlin