kind: Service
apiVersion: v1
metadata:
  name: webserver-service
spec:
  selector:
    app: webserver
  ports:
    - port: 5000 # Default port for image
---
kind: Service
apiVersion: v1
metadata:
  name: next-webserver-service
spec:
  selector:
    app: next-webserver
  ports:
    - port: 5000 # Default port for image
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress-https
  annotations:
    # Add the following line (staging first for testing, then apply the prod issuer)
    cert-manager.io/cluster-issuer: letsencrypt-prod # letsencrypt-staging
    acme.cert-manager.io/http01-edit-in-place: "true" # !!!This seems to be really important!!!

    ingress.kubernetes.io/ssl-redirect: "true"

spec:
  tls:
  - hosts:
    - bahnvorhersage.de
    - next.bahnvorhersage.de
    - trainconnectionprediction.de
    - next.trainconnectionprediction.de
    - edury.trainconnectionprediction.de
    - nextcloud.sfz-eningen.de
    - nextcloud.marcpanse.de
    - paralox-nextcloud.de
    - gitlab.sfz-eningen.de
    - gitlab.marcpanse.de
    - paralox-git.de
    - dashboard.sfz-eningen.de
    - overleaf.sfz-eningen.de
    - overleaf.marcpanse.de
    secretName: default-tls-secret
  rules:
  - host: "bahnvorhersage.de"
    http: &prod_webserver
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: webserver-service
              port:
                number: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80
  - host: "trainconnectionprediction.de"
    http: *prod_webserver
  - host: "next.bahnvorhersage.de"
    http: &test_webserver
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: next-webserver-service
              port:
                number: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: next-frontend-service
              port:
                number: 80
  - host: "next.trainconnectionprediction.de"
    http: *test_webserver

  - host: "edury.trainconnectionprediction.de"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: edury-decks-service
              port:
                number: 80
  - host: "overleaf.marcpanse.de"
    http: &overleaf
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sfz-overleaf
              port:
                number: 80
  - host: "overleaf.sfz-eningen.de"
    http: *overleaf

  - host: "gitlab.sfz-eningen.de"
    http: &gitlab
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sfz-gitlab
              port:
                number: 80
  - host: "gitlab.marcpanse.de"
    http: *gitlab
  - host: "paralox-git.de"
    http: *gitlab