apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
data:
  redis-config: |
    maxmemory 8GB
    maxmemory-policy allkeys-lru
    requirepass LHHhq7jivqfWmcLAeUvD39EPpaGAFVMm6yH5GeerBwWKjcgbL5iybKukLNL63Rs5
    bind * -::*
