#Ignore everything
*

#Except
!webserver/
!ml_models/
!database/
!helpers/
!data_analysis/
!webserverconfig.py
!api/

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/*~
**/__pycache__/
**/*.log
**/.DS_Store
**/Thumbs.db